#!/usr/bin/env python3
"""Report drift between the bundled English catalogs and every translation.

Authoring-time helper — never imported at runtime. Run it when the English
catalogs change, or before shipping a translation pass, to see what is new:

    python scripts/i18n_locale_drift.py                # every language
    python scripts/i18n_locale_drift.py --lang pt      # one language
    python scripts/i18n_locale_drift.py --lang pt --json

Reported per language:

* **new** — English keys the translation does not have yet.
* **extra** — keys the English catalog no longer has.
* **placeholder / line-breaks** — the translated value lost a ``{placeholder}``
  or a line break the English source uses to separate a headline from its body.
  These are bugs; ``--strict`` exits non-zero for them together with ``new``.
* **english-left** — values still byte-identical to English. Advisory: format
  strings (``ID: {id}``, ``OFF``) and product names are legitimately identical,
  so eyeball the list (``--list-english`` prints it).

The core surface is compared value-by-value against ``locales/en.yaml``. The
TUI/desktop surfaces publish only a key list (``locales/_keys.<surface>.json``,
regenerated by the TS packages' build), so for them only key drift is checked.

This tool never edits anything: a verified translation is a snapshot, and the
point is to name what the English source gained since that snapshot.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

ROOT = Path(__file__).resolve().parents[1]
LOCALES_DIR = ROOT / "locales"

# surface -> filename template, mirroring agent/i18n_layers.SURFACES
SURFACE_FILES = {
    "core": "{lang}.yaml",
    "tui": "{lang}.tui.yaml",
    "desktop": "{lang}.desktop.yaml",
}
KEY_EXPORTS = {"tui": "_keys.tui.json", "desktop": "_keys.desktop.json"}

PLACEHOLDER_RE = re.compile(r"\{([a-zA-Z_][a-zA-Z0-9_]*)\}")
ESCAPED_NEWLINE = "\\n"


def _load_document(path: Path) -> Any:
    import hermes_yaml as yaml

    with path.open("r", encoding="utf-8-sig") as handle:
        return yaml.safe_load(handle)


def _flatten(node: Any, prefix: str = "", out: Optional[Dict[str, str]] = None) -> Dict[str, str]:
    """Nested catalogs flattened to dotted keys; already-flat packs pass through."""
    out = {} if out is None else out
    for key, value in (node or {}).items():
        dotted = f"{prefix}.{key}" if prefix else str(key)
        if isinstance(value, dict):
            _flatten(value, dotted, out)
        else:
            out[dotted] = "" if value is None else str(value)
    return out


def _placeholders(value: str) -> Tuple[str, ...]:
    return tuple(sorted(PLACEHOLDER_RE.findall(value)))


def _line_breaks(value: str) -> int:
    """Line breaks in the rendered text, whatever way the catalog spells them.

    Core catalogs use a YAML double-quoted ``\\n`` escape, the TUI packs a literal
    backslash-n, and a block scalar holds a real newline; count both spellings so
    the comparison is about the message, not the encoding.
    """
    return value.count("\n") + value.count(ESCAPED_NEWLINE)


def _reference_keys(surface: str) -> Optional[set]:
    if surface == "core":
        return None  # compared against en.yaml values, not a key export
    export = LOCALES_DIR / KEY_EXPORTS[surface]
    if not export.is_file():
        return None
    data = json.loads(export.read_text(encoding="utf-8-sig"))
    keys = data.get("keys") if isinstance(data, dict) else data
    return {str(k) for k in keys} if isinstance(keys, list) else None


def _languages() -> List[str]:
    found = set()
    for template in SURFACE_FILES.values():
        suffix = template.replace("{lang}", "")
        for path in LOCALES_DIR.glob(f"*{suffix}"):
            name = path.name[: -len(suffix)]
            if name and not name.startswith("_"):
                found.add(name)
    return sorted(found - {"en"})


def _compare(surface: str, lang: str, english: Optional[Dict[str, str]]) -> Dict[str, Any]:
    path = LOCALES_DIR / SURFACE_FILES[surface].replace("{lang}", lang)
    if not path.is_file():
        return {"surface": surface, "present": False}

    translated = _flatten(_load_document(path))
    reference = _reference_keys(surface)
    english_keys = set(english) if english is not None else (reference or set(translated))

    missing = sorted(english_keys - set(translated))
    extra = sorted(set(translated) - english_keys) if reference is None else []

    placeholder_mismatch: List[str] = []
    newline_mismatch: List[str] = []
    untranslated: List[str] = []
    if english is not None:
        for key in sorted(set(english) & set(translated)):
            en_value, lang_value = english[key], translated[key]
            if _placeholders(en_value) != _placeholders(lang_value):
                placeholder_mismatch.append(key)
            elif _line_breaks(en_value) != _line_breaks(lang_value):
                newline_mismatch.append(key)
            elif en_value == lang_value:
                untranslated.append(key)

    return {
        "surface": surface,
        "present": True,
        "keys": len(translated),
        "missing": missing,
        "extra": extra,
        "placeholder_mismatch": placeholder_mismatch,
        "newline_mismatch": newline_mismatch,
        "untranslated": untranslated,
    }


def _contract_failures(report: Dict[str, Any]) -> int:
    return (
        len(report["missing"])
        + len(report["placeholder_mismatch"])
        + len(report["newline_mismatch"])
    )


def _first(keys: List[str], limit: int = 12) -> str:
    return ", ".join(keys[:limit]) + (" …" if len(keys) > limit else "")


def _print_human(reports: List[Dict[str, Any]], list_english: bool) -> None:
    for report in reports:
        if not report["present"]:
            continue
        print(
            f"{report['lang'] + '.' + report['surface']:22s} keys={report['keys']:5d} "
            f"new={len(report['missing']):3d} extra={len(report['extra']):3d} "
            f"placeholder={len(report['placeholder_mismatch']):3d} "
            f"line-breaks={len(report['newline_mismatch']):3d} "
            f"english-left={len(report['untranslated']):4d}"
        )
        for title, keys in (
            ("new (untranslated) keys", report["missing"]),
            ("keys dropped from English", report["extra"]),
            ("placeholder mismatch", report["placeholder_mismatch"]),
            ("line-break mismatch", report["newline_mismatch"]),
        ):
            if keys:
                print(f"    {title}: {_first(keys)}")
        if list_english and report["untranslated"]:
            print(f"    identical to English: {_first(report['untranslated'])}")


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--lang", action="append", help="language id (repeatable); default all")
    parser.add_argument("--json", action="store_true", help="emit JSON instead of a table")
    parser.add_argument(
        "--list-english", action="store_true",
        help="list every value still byte-identical to English",
    )
    parser.add_argument(
        "--strict", action="store_true",
        help="exit non-zero on contract drift (new keys, placeholders, line breaks)",
    )
    args = parser.parse_args(argv)

    english = _flatten(_load_document(LOCALES_DIR / "en.yaml"))
    reports = []
    for lang in args.lang or _languages():
        for surface in SURFACE_FILES:
            report = _compare(surface, lang, english if surface == "core" else None)
            report["lang"] = lang
            reports.append(report)

    if args.json:
        print(json.dumps(reports, ensure_ascii=False, indent=2))
    else:
        _print_human(reports, args.list_english)

    if args.strict:
        failures = sum(_contract_failures(r) for r in reports if r["present"])
        if failures:
            print(f"\n{failures} contract violation(s).", file=sys.stderr)
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

